### ISSUE TITLE
Push notification entitlements are not working properly in 4.0.0

### ISSUE THREAD

**Issue by nvahalik** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking-attribution#610]
I'm using Ionic Appflow to do builds. Recently updated the module to 4.0.0.

Since updating, I started receiving this message: 

> ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. If your app uses the Apple Push Notification service, make sure your App ID is enabled for Push Notification in the Provisioning Portal, and resubmit after signing your app with a Distribution provisioning profile that includes the "aps-environment" entitlement. Xcode does not automatically copy the aps-environment entitlement from provisioning profiles at build time. This behavior is intentional. To use this entitlement, either enable Push Notifications in the project editor's Capabilities pane, or manually add the entitlement to your entitlements file. For more information, see https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/HandlingRemoteNotifications.html#//apple_ref/doc/uid/TP40008194-CH6-SW1.

Reverting to 3.2.0 fixes this problem.

**Comment by sverdlov** [comment]
I have same problem even on 3.2.0.

**Comment by CodeWithOz** [comment]
This whole thing is a bit of a mess, and there are a number of interrelated bugs. @sverdlov there's a key in the entitlements file that can get overwritten due to the way some plugins handle their part of the build step. You can read [this thread](https://github.com/fastlane/fastlane/issues/15583#issuecomment-565759885) and follow all the links there to get a better idea of the bigger picture.

**Long story short**: Branch 4.0.0 fixes this and some other bugs, but Branch 4.0.0 also manifests another bug where you cannot build for iOS from the command line - you must use Xcode. For what it's worth, I've stayed on Cordova Android 8.0.0 and Branch 3.2.0, and that allows me to build successfully on both Android and iOS *after* applying the fix I described in the thread I linked. Hope this helps others.

**Comment by echo-branch** [comment]
This should be resolved in the latest release.
